version: '3.8'

services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - qdrant   # <- thêm qdrant

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:v1.7.3
    environment:
      - QDRANT__SERVICE__ENABLE_API_KEY=true
      - QDRANT_API_KEY=your-secret-api-key
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
